# Copyright 2023 Martin Bach
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

- hosts: all
  become: yes
  vars:
    mountDir: /vbox
    
  tasks:
  - name: upgrade all packages (this can take a while)
    yum:
      name: '*'
      state: latest

  - name: reboot to apply potential kernel changes
    reboot:  

  - name: install auxiliary packages
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - curl
      - bzip2
      - wget
      - unzip
      - kernel-uek-devel
      - oracle-epel-release-el8
  
  - name: install DKMS from the OL8 EPEL repository
    yum:
      name: dkms
      enablerepo: ol8_developer_EPEL
      state: present

  - name: create a temporary mount point for vbox guest additions  
    file:
      path: "{{ mountDir }}"
      state: directory
      
  # as per `guest_additions_path` in Packer's configuration file
  - name: mount guest additions ISO read-only
    mount:
      path: "{{ mountDir }}"
      src: /home/vagrant/VBoxGuestAdditions.iso
      fstype: iso9660
      opts: ro
      state: mounted

  # in case running kernel modules are detected using `failed_when` can prevent an error
  - name: execute guest additions script
    command: "{{ mountDir }}/VBoxLinuxAdditions.run"
    register: modules
    failed_when: 
    - modules.rc != 0
    - modules.rc != 2

  - name: unmount guest additions ISO
    mount:
      path: "{{ mountDir }}"
      state: absent

  - name: remove the temporary mount point  
    file:
      path: "{{ mountDir }}"
      state: absent